spring.application.name=backend

spring.datasource.url=jdbc:mysql://localhost:3306/learning_hub
spring.datasource.username=root
spring.datasource.password=ayush@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080

logging.level.org.springframework.security=TRACE

# ── Mail (Gmail SMTP) ──
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=palkarnayush@gmail.com
spring.mail.password=umyw aobx lomm mgbr
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true