spring.application.name=railway

spring.datasource.url=mysql://root:DDvjJwrjWELuNyFNVQhtnUQuyEfJgBCW@kodama.proxy.rlwy.net:34810/railway
spring.datasource.username=root
spring.datasource.password=DDvjJwrjWELuNyFNVQhtnUQuyEfJgBCW

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080

logging.level.org.springframework.security=TRACE

# ── Mail (Gmail SMTP) ──
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=palkarnayush@gmail.com
spring.mail.password=yuxy bqea hioe ajvl
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true